// Every balance number in STA-mble lives here and nowhere else (CLAUDE.md §5).
// Data only — no functions, so the Monte Carlo simulator can swap values wholesale (GDD 6-0).

import { SUIT_ORDER } from './types'
import type {
  CompanionDef,
  CompanionId,
  CompanionTier,
  ConstellationId,
  GameMode,
  LineAxis,
  MultiplierSpec,
  SuitId,
  WagerTier,
} from './types'

// ------------------------------------------------------------- core loop
// GDD 4-2

export const BOARD_SIZE = 5
export const HAND_SIZE = 8
export const MAX_PLACEMENTS_PER_TURN = 4
export const TURNS_PER_ROUND = 5

// --------------------------------------------------------------- deck
// GDD 4-2 (C-7): 5 suits × 10 = 50 cards.

export const INITIAL_DECK: Readonly<Record<SuitId, number>> = {
  GAC: 10,
  IMA: 10,
  GIN: 10,
  MIM: 10,
  ACR: 10,
}

/**
 * The stars the five suits are named after (GDD 3-1), in full.
 *
 * ★ One table, because two drifted. ORION'S WAGER wrote its questions with the
 * full name ("Ginan 칩") while every panel printed the three-letter code ("GIN"),
 * and nothing on screen joined them — a booth participant had no way to know the
 * question was about a row they were looking at (BOOTH-6a). GDD 8-1 now puts the
 * full name on STAR-CHART on both screens, and this is what all of them read.
 */
export const SUIT_STAR_NAMES: Readonly<Record<SuitId, string>> = {
  GAC: 'Gacrux',
  IMA: 'Imai',
  GIN: 'Ginan',
  MIM: 'Mimosa',
  ACR: 'Acrux',
}

export const BASE_CHIP_SCORE = 10

/**
 * The 10 special chips (GDD 3-2). Generated by an `i < j` walk over SUIT_ORDER,
 * so left/right is always scoring order — no hardcoded list to drift.
 */
export const SPECIAL_SUIT_PAIRS: readonly (readonly [SuitId, SuitId])[] = SUIT_ORDER.flatMap(
  (left, i) => SUIT_ORDER.slice(i + 1).map((right) => [left, right] as const),
)

/** GDD 3-3: 3 of the 4 orthogonal neighbours are chosen at scoring time. */
export const DRIFTER_DIRECTIONS_CHOSEN = 3
export const DRIFTER_MAX_PER_GAME = 1

// -------------------------------------------------------------- scoring
// GDD 5-2

/**
 * How multipliers on one line combine. GDD 5-2 fixes 'sum'; Phase 2 compares
 * all three by Monte Carlo, so this must stay a single swappable constant.
 *   sum            — 1.2 + 1.8 + 2.5 = 5.5
 *   product        — 1.2 × 1.8 × 2.5 = 5.4
 *   additive_delta — 1.0 + Σ(m − 1.0) = 3.5
 */
export type MultiplierStackMode = 'sum' | 'product' | 'additive_delta'
export const MULTIPLIER_STACK_MODE: MultiplierStackMode = 'sum'

/** Applied to chips of a suit that belong to no firing line (GDD 5-1). */
export const NO_LINE_MULTIPLIER = 1.0

// -------------------------------------------------------- constellations
// GDD 6

/** GDD 6-1: apex plus n cells down-left and n down-right. cells = 2n + 1. */
export const SHAPE_A_FORMS = [
  { n: 1, cells: 3 },
  { n: 2, cells: 5 },
] as const

/** GDD 6-2: horizontal base of `base` cells plus `stem` cells up from its centre. */
export const SHAPE_T_FORMS = [
  { base: 3, stem: 1, cells: 4 },
  { base: 3, stem: 2, cells: 5 },
  { base: 5, stem: 1, cells: 6 },
  { base: 5, stem: 2, cells: 7 },
] as const

/** Aquarius, keyed by cell count (GDD 6-1). */
export const SHAPE_A_MULTIPLIERS: Readonly<Record<number, number>> = {
  3: 2.0,
  5: 3.5,
}

/** Virgo, keyed by cell count (GDD 6-2). */
export const SHAPE_T_MULTIPLIERS: Readonly<Record<number, number>> = {
  4: 1.5,
  5: 1.9,
  6: 2.2,
  7: 2.5,
}

export const CONSTELLATION_MULTIPLIERS: Readonly<Record<ConstellationId, MultiplierSpec>> = {
  aries: { kind: 'fixed', value: 1.2 },
  taurus: { kind: 'fixed', value: 2.1 },
  gemini: { kind: 'fixed', value: 1.5 },
  cancer: { kind: 'fixed', value: 1.1 },
  leo: { kind: 'fixed', value: 2.5 },
  virgo: { kind: 'bySize', table: SHAPE_T_MULTIPLIERS },
  libra: { kind: 'fixed', value: 1.2 },
  scorpio: { kind: 'fixed', value: 3.0 },
  sagittarius: { kind: 'fixed', value: 2.5 },
  capricorn: { kind: 'fixed', value: 1.8 },
  aquarius: { kind: 'bySize', table: SHAPE_A_MULTIPLIERS },
  pisces: { kind: 'fixed', value: 1.8 },
}

export interface ConstellationRule {
  readonly axis: LineAxis
  /** Run length in cells. `null` for shape and global axes, whose geometry is in SHAPE_*_FORMS. */
  readonly length: number | null
  /** `true` = exactly `length`; `false` = `length` or more. */
  readonly exact: boolean
}

export const CONSTELLATION_RULES: Readonly<Record<ConstellationId, ConstellationRule>> = {
  aries: { axis: 'vertical', length: 3, exact: false },
  taurus: { axis: 'diagonal', length: 4, exact: false },
  gemini: { axis: 'diagonal', length: 3, exact: false },
  cancer: { axis: 'global', length: null, exact: false },
  leo: { axis: 'horizontal', length: 5, exact: true },
  virgo: { axis: 'shape_T', length: null, exact: false },
  libra: { axis: 'horizontal', length: 3, exact: false },
  scorpio: { axis: 'diagonal', length: 5, exact: true },
  sagittarius: { axis: 'vertical', length: 5, exact: true },
  capricorn: { axis: 'vertical', length: 4, exact: false },
  aquarius: { axis: 'shape_A', length: null, exact: false },
  pisces: { axis: 'horizontal', length: 4, exact: false },
}

/** Korean UI labels (CLAUDE.md §8). */
export const CONSTELLATION_NAMES: Readonly<Record<ConstellationId, string>> = {
  aries: '양자리',
  taurus: '황소자리',
  gemini: '쌍둥이자리',
  cancer: '게자리',
  leo: '사자자리',
  virgo: '처녀자리',
  libra: '천칭자리',
  scorpio: '전갈자리',
  sagittarius: '궁수자리',
  capricorn: '염소자리',
  aquarius: '물병자리',
  pisces: '물고기자리',
}

export const OWNED_CONSTELLATION_LIMIT = 4

/**
 * GDD 13-5: the player starts holding one of these. Both are ×1.2 over a run of 3
 * and differ only in axis, so the pick costs no balance — it exists to give R1 a
 * decision and a score that responds to placement.
 */
export const STARTING_CONSTELLATION_CHOICES = ['aries', 'libra'] as const

// ------------------------------------------------------------ companions
// GDD 7

export const OWNED_COMPANION_LIMIT = 2

/** Shop draw weights in percent; sums to 100 and is shown in-game (GDD 7-1). */
export const COMPANION_TIER_WEIGHTS: Readonly<Record<CompanionTier, number>> = {
  rare: 45,
  superRare: 27,
  epic: 17,
  mythic: 8,
  legendary: 3,
}

export const COMPANION_TIER_PRICES: Readonly<Record<CompanionTier, number>> = {
  rare: 6,
  superRare: 9,
  epic: 13,
  mythic: 18,
  legendary: 25,
}

/** GDD 7-1-b: id/name/tier/price/description at P0; effect parameters at P4. */
export const COMPANIONS: Readonly<Record<CompanionId, CompanionDef>> = {
  // ⭐ Legendary — 초거성
  cloverSupergiant: {
    id: 'cloverSupergiant',
    name: '클로버 초거성',
    tier: 'legendary',
    price: COMPANION_TIER_PRICES.legendary,
    description: '성단 상하좌우 끝이 연결되어(토러스), 반대편 칩과도 별자리가 이어진다',
  },
  lawOfLargeNumbersSupergiant: {
    id: 'lawOfLargeNumbersSupergiant',
    name: '큰수의법칙 초거성',
    tier: 'legendary',
    price: COMPANION_TIER_PRICES.legendary,
    description: '주기가 끝날 때마다 모든 배율이 +0.1 영구 누적된다',
  },

  // 🌟 Mythic — 주계열성
  expectedValueMainSequence: {
    id: 'expectedValueMainSequence',
    name: '기댓값 주계열성',
    tier: 'mythic',
    price: COMPANION_TIER_PRICES.mythic,
    description: '떠돌이 조각이 항상 4가지 경우 중 최고 점수로 판정된다',
  },
  pulsatingMainSequence: {
    id: 'pulsatingMainSequence',
    name: '맥동 주계열성',
    tier: 'mythic',
    price: COMPANION_TIER_PRICES.mythic,
    description: '턴마다 점수 배율이 ×0.7 → ×1.8 순으로 번갈아 적용된다',
  },
  supernovaMainSequence: {
    id: 'supernovaMainSequence',
    name: '초신성 주계열성',
    tier: 'mythic',
    price: COMPANION_TIER_PRICES.mythic,
    description: '주기 마지막 턴 점수가 ×2가 된다',
  },
  binaryMainSequence: {
    id: 'binaryMainSequence',
    name: '쌍성 주계열성',
    tier: 'mythic',
    price: COMPANION_TIER_PRICES.mythic,
    description: '동반성 슬롯이 1개 늘어난다 (최대 3개)',
  },

  // 💫 Epic — 원시별
  duckProtostar: {
    id: 'duckProtostar',
    name: '오리 원시별',
    tier: 'epic',
    price: COMPANION_TIER_PRICES.epic,
    description: '별자리가 발동될 때마다 무작위 칩의 가치가 상승한다',
  },
  complementProtostar: {
    id: 'complementProtostar',
    name: '여사건 원시별',
    tier: 'epic',
    price: COMPANION_TIER_PRICES.epic,
    description: "ORION'S WAGER를 틀려도 보상의 절반을 획득한다",
  },
  samplingProtostar: {
    id: 'samplingProtostar',
    name: '표본추출 원시별',
    tier: 'epic',
    price: COMPANION_TIER_PRICES.epic,
    description: '매 턴 손패가 8장 → 10장이 된다',
  },
  conditionalProtostar: {
    id: 'conditionalProtostar',
    name: '조건부 원시별',
    tier: 'epic',
    price: COMPANION_TIER_PRICES.epic,
    description: '공허에 가장 적게 남은 문양의 칩 점수가 ×2가 된다',
  },
  redProtostar: {
    id: 'redProtostar',
    name: '적색 원시별',
    tier: 'epic',
    price: COMPANION_TIER_PRICES.epic,
    description: 'Ginan 칩의 기본 점수가 10 → 18이 된다',
  },
  darkProtostar: {
    id: 'darkProtostar',
    name: '암흑 원시별',
    tier: 'epic',
    price: COMPANION_TIER_PRICES.epic,
    description: 'γένεσις하지 않은 조각 1장당 St4RDu3t +1',
  },

  // ✨ Super Rare — 성운
  sampleMeanNebula: {
    id: 'sampleMeanNebula',
    name: '표본평균 성운',
    tier: 'superRare',
    price: COMPANION_TIER_PRICES.superRare,
    description: '최근 3턴 평균 점수의 20%를 매 턴 보너스로 받는다',
  },
  withoutReplacementNebula: {
    id: 'withoutReplacementNebula',
    name: '비복원 성운',
    tier: 'superRare',
    price: COMPANION_TIER_PRICES.superRare,
    description: 'γένεσις한 칩이 공허로 돌아오지 않는다 (공허 확률이 급격히 변한다)',
  },
  independentTrialNebula: {
    id: 'independentTrialNebula',
    name: '독립시행 성운',
    tier: 'superRare',
    price: COMPANION_TIER_PRICES.superRare,
    description: '매 턴 20% 확률로 그 턴 점수가 ×1.5가 된다',
  },
  unstableNebula: {
    id: 'unstableNebula',
    name: '불안정 성운',
    tier: 'superRare',
    price: COMPANION_TIER_PRICES.superRare,
    description: '매 턴 점수에 ×0.5 ~ ×2.0의 무작위 배율이 곱해진다',
  },
  eclipticNebula: {
    id: 'eclipticNebula',
    name: '황도 성운',
    tier: 'superRare',
    price: COMPANION_TIER_PRICES.superRare,
    description: '별자리 보유 한도가 4 → 5로 늘어난다',
  },
  mirrorNebula: {
    id: 'mirrorNebula',
    name: '거울 성운',
    tier: 'superRare',
    price: COMPANION_TIER_PRICES.superRare,
    description: '성단 좌우 대칭 위치에 같은 칩이 있으면 둘 다 +50%',
  },
  magneticNebula: {
    id: 'magneticNebula',
    name: '자기장 성운',
    tier: 'superRare',
    price: COMPANION_TIER_PRICES.superRare,
    description: '같은 문양끼리 인접할 때마다 각각 +5점',
  },
  cumulusNebula: {
    id: 'cumulusNebula',
    name: '적운 성운',
    tier: 'superRare',
    price: COMPANION_TIER_PRICES.superRare,
    description: 'MЦLГЦS 조각의 두 판정이 모두 라인에 포함되면 +30%',
  },

  // 🔹 Rare — 가스
  sampleSizeGas: {
    id: 'sampleSizeGas',
    name: '표본크기 가스',
    tier: 'rare',
    price: COMPANION_TIER_PRICES.rare,
    description: '주기마다 공허에 무작위 칩 2장이 추가된다',
  },
  relativeFrequencyGas: {
    id: 'relativeFrequencyGas',
    name: '상대도수 가스',
    tier: 'rare',
    price: COMPANION_TIER_PRICES.rare,
    description: '이번 주기에 가장 많이 γένεσις한 문양이 개당 +15점',
  },
  dustGas: {
    id: 'dustGas',
    name: '먼지 가스',
    tier: 'rare',
    price: COMPANION_TIER_PRICES.rare,
    description: '모든 칩의 기본 점수 +2',
  },
  blueGas: {
    id: 'blueGas',
    name: '청색 가스',
    tier: 'rare',
    price: COMPANION_TIER_PRICES.rare,
    description: 'Imai 칩의 기본 점수가 10 → 16',
  },
  greenGas: {
    id: 'greenGas',
    name: '녹색 가스',
    tier: 'rare',
    price: COMPANION_TIER_PRICES.rare,
    description: 'Gacrux 칩의 기본 점수가 10 → 16',
  },
  purpleGas: {
    id: 'purpleGas',
    name: '자색 가스',
    tier: 'rare',
    price: COMPANION_TIER_PRICES.rare,
    description: 'Mimosa 칩의 기본 점수가 10 → 16',
  },
  blackGas: {
    id: 'blackGas',
    name: '흑색 가스',
    tier: 'rare',
    price: COMPANION_TIER_PRICES.rare,
    description: 'Acrux 칩의 기본 점수가 10 → 16',
  },
  planetaryGas: {
    id: 'planetaryGas',
    name: '행성상 가스',
    tier: 'rare',
    price: COMPANION_TIER_PRICES.rare,
    description: '성단 네 모서리에 γένεσις된 칩이 ×1.5',
  },
  coreGas: {
    id: 'coreGas',
    name: '중심핵 가스',
    tier: 'rare',
    price: COMPANION_TIER_PRICES.rare,
    description: '성단 정중앙 칸의 칩이 ×2.5',
  },
  cometGas: {
    id: 'cometGas',
    name: '혜성 가스',
    tier: 'rare',
    price: COMPANION_TIER_PRICES.rare,
    description: '주기 첫 턴 점수가 ×1.5',
  },
}

// -------------------------------------------------------------- economy
// GDD 9

export const STARDUST_REWARDS = {
  /** Round clear pays `base + roundNumber × perRound` (GDD 9-1). */
  roundClearBase: 5,
  roundClearPerRound: 1,
  /** Overshoot pays `floor(excess / divisor)`, capped at `max`. */
  overshootDivisor: 100,
  overshootMax: 5,
  wagerCorrect: 2,
  oracleCorrect: 1,
} as const

export const SHOP_PRICES = {
  addBasicChip: 3,
  removeBasicChip: 4,
  specialChip: 8,
  // The drifter has no price: иєвυℓα hands it over at the first shop (GDD 13-4).
  constellation: 10,
  companion: COMPANION_TIER_PRICES,
  /** Reroll costs `base`, then rises by `increment` per use (GDD 9-2). */
  rerollBase: 2,
  rerollIncrement: 1,
} as const

/**
 * Items on offer per shop visit (GDD 9-3).
 *
 * No drifter slot: GDD 13-4 turned it from stock into a gift at the first
 * meeting, and a dead `drifterChips` here was a standing invitation to put it
 * back on a shelf and quietly break that rule.
 */
export const SHOP_SLOTS = {
  specialChips: 4,
  constellations: 2,
  companions: 2,
} as const

/**
 * Two flags, because "on the shelf" and "can be bought" are different questions
 * and P4-A needs one true and the other false.
 *
 * The shop shows the two companion slots so the player can see what the system
 * is and what a tier costs (GDD 7-1's published odds are a teaching device, and
 * they teach nothing behind an empty slot). Buying stays shut until the effect
 * parameters exist at P4-B (GDD 7-1-b) — selling a companion that does nothing
 * would take stardust for no effect.
 */
export const COMPANIONS_STOCKED = true
export const COMPANIONS_ENABLED = false

// ------------------------------------------------- probability layer
// GDD 8

/** The first N wagers of a game are forced as tutorial (GDD 8-2). */
export const FORCED_WAGER_COUNT = 3

/** Question tier by round, indexed by `round - 1` (GDD 8-2). */
export const WAGER_TIER_BY_ROUND: readonly WagerTier[] = [
  'comparison',
  'comparison',
  'complement',
  'complement',
  'complement',
  'conditional',
  'conditional',
  'conditional',
]

/**
 * How far apart a wager's two quantities have to be before it is worth asking
 * (GDD 8-2). 0.05 is roughly a two-chip difference in a 40-50 card deck; one
 * chip moves the chance of drawing a suit by about 0.03, and a question that
 * close cannot be called by a student who did the arithmetic correctly.
 *
 * Exactly equal quantities are exempt, since equal counts are read straight off
 * STAR-CHART and "the same" is then the whole answer.
 */
export const WAGER_MIN_GAP = 0.05

/**
 * What a 여사건 question may be asked against (GDD 8-2).
 *
 * 0.05 is in the list for balance, not for variety. On a deck the round has not
 * touched, "not one of a suit in eight draws" is 0.143 — above 0.1 by less than
 * WAGER_MIN_GAP, so the 0.1 question is dropped as too close to call and every
 * remaining threshold answers NO. A player would only have to notice that the
 * first wager of a round is never YES.
 */
export const WAGER_COMPLEMENT_THRESHOLDS: readonly number[] = [0.05, 0.1, 0.25, 0.5, 0.75]

/** Correct DRIFT ORACLE answer adds this fraction to that turn's drifter score (GDD 8-3). */
export const DRIFT_ORACLE_BONUS = 0.5

// ------------------------------------------------------- CONSTELLATION LOG
// GDD 8-4

/**
 * What a player who reads nothing and picks at random scores on the wager.
 *
 * Not a balance knob — it follows from the wager being one of two answers
 * (GDD 8-2), and `generateWager` picking the side it wants first, which balances
 * YES and NO by construction. It is here rather than in the report so that a
 * wager with a third answer could not leave the baseline behind.
 */
export const WAGER_GUESS_RATE = 0.5

/**
 * How wide "the range a sample this size usually lands in" is drawn, in standard
 * deviations (GDD 8-4). Two of them is about 95 in 100.
 *
 * A display choice, not a balance one: it decides how forgiving the band on the
 * report looks, and nothing about the game. It is deliberately generous — the
 * report's job is to stop a middle schooler reading an ordinary gap as a broken
 * theory, so a band that is slightly too wide fails in the safe direction.
 */
export const REPORT_BAND_SIGMA = 2

// --------------------------------------------------- settlement pacing
// GDD 5-1, 12-1

/**
 * How long one suit's beat lasts in the settlement, and how long the finished
 * settlement is left on screen before the turn advances by itself (BOOTH-9b).
 *
 * ★ These are presentation timings in a file of balance numbers, and they are here
 * on purpose: they *are* a balance number for the booth. GDD 12-1 scores the booth
 * on throughput, and BOOTH-9b made the settlement advance on a timer rather than on
 * a click — so 15 settlements a run × (five suit beats + this wait) is now a fixed
 * cost in the 28-minute budget rather than something a fast player can skip. A
 * figure that decides how long a participant holds a seat belongs where the round
 * count is, not buried in an animation module.
 *
 * The wait is measured from the end of the walk, not from its start: the walk's
 * length varies with how many suits scored (GDD 5-1 omits the ones worth nothing),
 * so timing from the start would give a short settlement a long tail and a long one
 * almost none.
 */
export const SUIT_STEP_MS = 600
export const SETTLEMENT_HOLD_MS = 2000

// ---------------------------------------------------------------- modes
// GDD 10, 12-3, 12-4

export interface ModePreset {
  readonly TOTAL_ROUNDS: number
  /** Cumulative round-score target, indexed by `round - 1`. */
  readonly TARGET_SCORES: readonly number[]
}

export const MODE_PRESETS: Readonly<Record<GameMode, ModePreset>> = {
  // Back-solved by `npm run sim -- --solve` against GDD 13-3, replacing the
  // hand-drawn ×1.62 curve whose last two rounds were above the rules' ceiling.
  // The curve is nearly flat because the board resets every round and the
  // constellation limit is 4 — scores do not compound the way the old curve assumed.
  full: {
    TOTAL_ROUNDS: 8,
    TARGET_SCORES: [490, 630, 640, 880, 1080, 1250, 1330, 1530],
  },
  // ★ No longer full's rounds 1–3. BOOTH-9a raised the booth curve to
  // [600, 900, 2000] on the strength of the designer playing it — the back-solved
  // figures were read off a bot's score distribution, and a person who reads
  // STAR-CHART and plans two turns ahead out-scores `smart` by enough that the old
  // R3 of 640 was cleared on the way past. GDD 12-4 still governs: the rule is the
  // clear rate, not any individual figure, and 13-6 records what these measure.
  booth: {
    TOTAL_ROUNDS: 3,
    TARGET_SCORES: [600, 900, 2000],
  },
}

export const DEFAULT_MODE: GameMode = 'full'

export const TOTAL_ROUNDS = MODE_PRESETS.full.TOTAL_ROUNDS
export const TARGET_SCORES = MODE_PRESETS.full.TARGET_SCORES
